name: Building Documentation

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    if: "contains(github.event.head_commit.message, 'build-documentation')"
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}

    - name: Install Doxygen
      run: sudo apt-get install doxygen -y
      shell: bash

    - name: Generating doxygen documentation
      run: doxygen
      shell: bash
    
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "built documentation"